In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', 50)
sns.set_style('whitegrid')

In [42]:
matches_all = pd.read_csv('epl_raw.csv')
matches_all.shape

(2280, 29)

In [43]:
matches_all.head(3)

,league,season,game,league_id,season_id,game_id,date,home_team_id,away_team_id,home_team,away_team,away_team_code,home_team_code,home_points,home_expected_points,home_goals,home_xg,home_np_xg,home_np_xg_difference,home_ppda,home_deep_completions,away_points,away_expected_points,away_goals,away_xg,away_np_xg,away_np_xg_difference,away_ppda,away_deep_completions
0,EPL,2021,2020-09-12 Crystal Palace-Southampton,1,2020,14087,2020-09-12 14:00:00,78,74,Crystal Palace,Southampton,SOU,CRY,3,1.4770,1,1.395690,1.395690,0.133020,17.333333,1,0,1.2208,0,1.262670,1.262670,-0.133020,3.608696,14
1,EPL,2021,2020-09-12 Fulham-Arsenal,1,2020,14086,2020-09-12 11:30:00,228,83,Fulham,Arsenal,ARS,FLH,0,0.0587,0,0.126327,0.126327,-2.036543,32.692308,0,3,2.8937,3,2.162870,2.162870,2.036543,21.928571,11
2,EPL,2021,2020-09-12 Liverpool-Leeds,1,2020,14090,2020-09-12 16:30:00,87,245,Liverpool,Leeds,LED,LIV,3,2.9270,4,3.154120,1.631790,1.361977,9.935484,19,0,0.0434,3,0.269813,0.269813,-1.361977,9.333333,2

In [44]:
matches_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2280 entries, 0 to 2279
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   league                 2280 non-null   object
 1   season                 2280 non-null   int64
 2   game                   2280 non-null   object
 3   league_id              2280 non-null   int64
 4   season_id              2280 non-null   int64
 5   game_id                2280 non-null   int64
 6   date                   2280 non-null   object
 7   home_team_id           2280 non-null   int64
 8   away_team_id           2280 non-null   int64
 9   home_team              2280 non-null   object
 10  away_team              2280 non-null   object
 11  away_team_code         2280 non-null   object
 12  home_team_code         2280 non-null   object
 13  home_points            2280 non-null   int64
 14  home_expected_points   2280 non-null   float64
 15  home_goals             2280 non-null   int64
 16  home_xg                2280 non-null   float64
 17  home_np_xg             2280 non-null   float64
 18  home_np_xg_difference  2280 non-null   float64
 19  home_ppda              2280 non-null   float64
 20  home_deep_completions  2280 non-null   int64
 21  away_points            2280 non-null   int64
 22  away_expected_points   2280 non-null   float64
 23  away_goals             2280 non-null   int64
 24  away_xg                2280 non-null   float64
 25  away_np_xg             2280 non-null   float64
 26  away_np_xg_difference  2280 non-null   float64
 27  away_ppda              2280 non-null   float64
 28  away_deep_completions  2280 non-null   int64
dtypes: float64(10), int64(12), object(7)
memory usage: 516.7+ KB

In [45]:
matches_all['season'].unique()

array([2021, 2122, 2223, 2324, 2425, 2526])

In [46]:
season = matches_all[matches_all['season'] == 2526].copy()
season.shape

(380, 29)

In [47]:
season.isnull().sum()

league                   0
season                   0
game                     0
league_id                0
season_id                0
game_id                  0
date                     0
home_team_id             0
away_team_id             0
home_team                0
away_team                0
away_team_code           0
home_team_code           0
home_points              0
home_expected_points     0
home_goals               0
home_xg                  0
home_np_xg               0
home_np_xg_difference    0
home_ppda                0
home_deep_completions    0
away_points              0
away_expected_points     0
away_goals               0
away_xg                  0
away_np_xg               0
away_np_xg_difference    0
away_ppda                0
away_deep_completions    0
dtype: int64

In [48]:
pd.concat([season['home_team'], season['away_team']]).nunique()

20

In [49]:
players = pd.read_csv('players_data_light-2025_2026.csv')
players.shape

(2839, 53)

In [50]:
players['Comp'].value_counts()

Comp
es La Liga            611
it Serie A            609
fr Ligue 1            561
eng Premier League    551
de Bundesliga         507
Name: count, dtype: int64

In [51]:
players_epl = players[players['Comp'] == 'eng Premier League'].copy()
players_epl.shape

(551, 53)

In [52]:
players_epl['Squad'].nunique()

20

In [53]:
players_epl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 551 entries, 0 to 2835
Data columns (total 53 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Rk                    551 non-null    int64
 1   Player                551 non-null    object
 2   Nation                551 non-null    object
 3   Pos                   551 non-null    object
 4   Squad                 551 non-null    object
 5   Comp                  551 non-null    object
 6   Age                   551 non-null    float64
 7   Born                  551 non-null    float64
 8   MP                    551 non-null    int64
 9   Starts                551 non-null    int64
 10  Min                   551 non-null    int64
 11  90s                   551 non-null    float64
 12  Gls                   551 non-null    int64
 13  Ast                   551 non-null    int64
 14  G+A                   551 non-null    int64
 15  G-PK                  551 non-null    int64
 16  PK                    551 non-null    int64
 17  PKatt                 551 non-null    int64
 18  CrdY                  551 non-null    int64
 19  CrdR                  551 non-null    int64
 20  G+A-PK                551 non-null    float64
 21  Sh                    551 non-null    int64
 22  SoT                   551 non-null    int64
 23  SoT%                  456 non-null    float64
 24  Sh/90                 551 non-null    float64
 25  SoT/90                551 non-null    float64
 26  G/Sh                  456 non-null    float64
 27  G/SoT                 393 non-null    float64
 28  PK_stats_shooting     551 non-null    int64
 29  PKatt_stats_shooting  551 non-null    int64
 30  Crs                   551 non-null    int64
 31  TklW                  551 non-null    int64
 32  Int                   551 non-null    int64
 33  Fld                   551 non-null    int64
 34  CrdY_stats_misc       551 non-null    int64
 35  CrdR_stats_misc       551 non-null    int64
 36  2CrdY                 551 non-null    int64
 37  Fls                   551 non-null    int64
 38  OG                    551 non-null    int64
 39  GA                    40 non-null     float64
 40  GA90                  40 non-null     float64
 41  SoTA                  40 non-null     float64
 42  Saves                 40 non-null     float64
 43  Save%                 39 non-null     float64
 44  W                     40 non-null     float64
 45  D                     40 non-null     float64
 46  L                     40 non-null     float64
 47  CS                    40 non-null     float64
 48  CS%                   39 non-null     float64
 49  PKatt_stats_keeper    40 non-null     float64
 50  PKA                   40 non-null     float64
 51  PKsv                  40 non-null     float64
 52  PKm                   40 non-null     float64
dtypes: float64(23), int64(25), object(5)
memory usage: 232.5+ KB

In [54]:
players_epl.isnull().sum().sort_values(ascending=False).head(15)

CS%                   512
Save%                 512
GA                    511
D                     511
CS                    511
PKsv                  511
PKm                   511
PKatt_stats_keeper    511
PKA                   511
Saves                 511
W                     511
SoTA                  511
GA90                  511
L                     511
G/SoT                 158
dtype: int64

In [55]:
players_epl[['Gls','Ast','Min','Sh','SoT']].describe()

              Gls         Ast          Min          Sh         SoT
count  551.000000  551.000000   551.000000  551.000000  551.000000
mean     1.823956    1.248639  1362.834846   17.234120    5.773140
std      3.138014    1.906418  1026.840443   19.652379    7.701788
min      0.000000    0.000000     1.000000    0.000000    0.000000
25%      0.000000    0.000000   410.000000    2.000000    0.000000
50%      1.000000    1.000000  1277.000000   12.000000    3.000000
75%      2.000000    2.000000  2139.000000   25.000000    8.000000
max     27.000000   21.000000  3420.000000  126.000000   59.000000

In [56]:
players_epl['Pos'].unique()

array(['MF,FW', 'MF', 'DF', 'FW', 'GK', 'FW,MF', 'MF,DF', 'DF,MF'],
      dtype=object)

In [57]:
teams_players = set(players_epl['Squad'].unique())
teams_matches = set(matches_all[matches_all['season']==2526]['home_team'].unique())
print("Trong players nhưng không có trong matches:", teams_players - teams_matches)
print("Trong matches nhưng không có trong players:", teams_matches - teams_players)

Trong players nhưng không có trong matches: {'Leeds United', 'West Ham United', 'Manchester Utd', 'Wolves', 'Tottenham Hotspur'}
Trong matches nhưng không có trong players: {'West Ham', 'Tottenham', 'Manchester United', 'Leeds', 'Wolverhampton Wanderers'}

In [58]:
team_name_map = {
    'Tottenham Hotspur': 'Tottenham',
    'Manchester Utd': 'Manchester United',
    'West Ham United': 'West Ham',
    'Leeds United': 'Leeds',
    'Wolves': 'Wolverhampton Wanderers',
}

players_epl['Squad'] = players_epl['Squad'].replace(team_name_map)

In [59]:
teams_players = set(players_epl['Squad'].unique())
teams_matches = set(matches_all[matches_all['season']==2526]['home_team'].unique())
print(teams_players - teams_matches)
print(teams_matches - teams_players)

set()
set()

In [60]:
season = matches_all[matches_all['season'] == 2526].copy()
season['date'] = pd.to_datetime(season['date'])
season = season.sort_values('date').reset_index(drop=True)

In [61]:
season['date'].dtype

dtype('<M8[ns]')

In [62]:
def normalize_pos(pos):
    return ','.join(sorted(pos.split(',')))

players_epl['Pos'] = players_epl['Pos'].apply(normalize_pos)
players_epl['Pos'].unique()

array(['FW,MF', 'MF', 'DF', 'FW', 'GK', 'DF,MF'], dtype=object)

In [63]:
season['home_result'] = season['home_points'].map({3: 'W', 1: 'D', 0: 'L'})
season['away_result'] = season['away_points'].map({3: 'W', 1: 'D', 0: 'L'})
season[['home_team','away_team','home_goals','away_goals','home_result','away_result']].head()

,home_team,away_team,home_goals,away_goals,home_result,away_result
0,Liverpool,Bournemouth,4,2,W,L
1,Aston Villa,Newcastle United,0,0,D,D
2,Brighton,Fulham,1,1,D,D
3,Sunderland,West Ham,3,0,W,L
4,Tottenham,Burnley,3,0,W,L

In [64]:
home_view = season[['date','home_team','away_team','home_points','home_goals','away_goals','home_xg','away_xg']].copy()
home_view.columns = ['date','team','opponent','points','goals_for','goals_against','xg_for','xg_against']
home_view['venue'] = 'Home'

home_view.head()

,date,team,opponent,points,goals_for,goals_against,xg_for,xg_against,venue
0,2025-08-15 19:00:00,Liverpool,Bournemouth,3,4,2,2.330070,1.573030,Home
1,2025-08-16 11:30:00,Aston Villa,Newcastle United,1,0,0,0.318601,1.400980,Home
2,2025-08-16 14:00:00,Brighton,Fulham,1,1,1,1.440080,0.902883,Home
3,2025-08-16 14:00:00,Sunderland,West Ham,3,3,0,0.724368,0.558948,Home
4,2025-08-16 14:00:00,Tottenham,Burnley,3,3,0,1.978580,0.734138,Home

In [65]:
away_view = season[['date', 'away_team', 'home_team', 'away_points', 'away_goals', 'home_goals', 'away_xg', 'home_xg']].copy()
away_view.columns = ['date', 'team', 'opponent', 'points', 'goals_for', 'goals_against', 'xg_for', 'xg_against']
away_view['venue'] = 'Away'

away_view.head()

,date,team,opponent,points,goals_for,goals_against,xg_for,xg_against,venue
0,2025-08-15 19:00:00,Bournemouth,Liverpool,0,2,4,1.573030,2.330070,Away
1,2025-08-16 11:30:00,Newcastle United,Aston Villa,1,0,0,1.400980,0.318601,Away
2,2025-08-16 14:00:00,Fulham,Brighton,1,1,1,0.902883,1.440080,Away
3,2025-08-16 14:00:00,West Ham,Sunderland,0,0,3,0.558948,0.724368,Away
4,2025-08-16 14:00:00,Burnley,Tottenham,0,0,3,0.734138,1.978580,Away

In [66]:
team_matches = pd.concat([home_view, away_view], ignore_index=True)
team_matches = team_matches.sort_values(['team', 'date']).reset_index(drop=True)
team_matches.shape

(760, 9)

In [67]:
len(team_matches) == len(home_view) + len(away_view)

True

In [68]:
team_matches['team'].value_counts()

team
Arsenal                    38
Aston Villa                38
Bournemouth                38
Brentford                  38
Brighton                   38
Burnley                    38
Chelsea                    38
Crystal Palace             38
Everton                    38
Fulham                     38
Leeds                      38
Liverpool                  38
Manchester City            38
Manchester United          38
Newcastle United           38
Nottingham Forest          38
Sunderland                 38
Tottenham                  38
West Ham                   38
Wolverhampton Wanderers    38
Name: count, dtype: int64

In [69]:
team_matches['result'] = team_matches['points'].map({3: 'W', 1: 'D', 0: 'L'})
team_matches['goal_diff'] = team_matches['goals_for'] - team_matches['goals_against']
team_matches['xg_diff'] = team_matches['xg_for'] - team_matches['xg_against']

In [70]:
team_matches['matchweek'] = team_matches.groupby('team').cumcount() + 1
team_matches['cum_points'] = team_matches.groupby('team')['points'].cumsum()

In [71]:
team_matches[team_matches['team'] == 'Arsenal'][['date','opponent','venue','result','points','matchweek','cum_points']].head(10)

,date,opponent,venue,result,points,matchweek,cum_points
0,2025-08-17 15:30:00,Manchester United,Away,W,3,1,3
1,2025-08-23 16:30:00,Leeds,Home,W,3,2,6
2,2025-08-31 15:30:00,Liverpool,Away,L,0,3,6
3,2025-09-13 11:30:00,Nottingham Forest,Home,W,3,4,9
4,2025-09-21 15:30:00,Manchester City,Home,D,1,5,10
5,2025-09-28 15:30:00,Newcastle United,Away,W,3,6,13
6,2025-10-04 14:00:00,West Ham,Home,W,3,7,16
7,2025-10-18 16:30:00,Fulham,Away,W,3,8,19
8,2025-10-26 13:00:00,Crystal Palace,Home,W,3,9,22
9,2025-11-01 15:00:00,Burnley,Away,W,3,10,25

In [72]:
team_matches['form_pts_last5'] = (
    team_matches.groupby('team')['points']
    .rolling(5, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
)

In [73]:
team_matches[team_matches['team'] == 'Arsenal'][['date','opponent','result','points','form_pts_last5']].head(10)

                 date           opponent result  points  form_pts_last5
0 2025-08-17 15:30:00  Manchester United      W       3             3.0
1 2025-08-23 16:30:00              Leeds      W       3             6.0
2 2025-08-31 15:30:00          Liverpool      L       0             6.0
3 2025-09-13 11:30:00  Nottingham Forest      W       3             9.0
4 2025-09-21 15:30:00    Manchester City      D       1            10.0
5 2025-09-28 15:30:00   Newcastle United      W       3            10.0
6 2025-10-04 14:00:00           West Ham      W       3            10.0
7 2025-10-18 16:30:00             Fulham      W       3            13.0
8 2025-10-26 13:00:00     Crystal Palace      W       3            13.0
9 2025-11-01 15:00:00            Burnley      W       3            15.0

In [74]:
players_epl['Ast_per90'] = players_epl['Ast'] / players_epl['Min'] * 90
players_epl['Sh_per90'] = players_epl['Sh'] / players_epl['Min'] * 90
players_epl['Gls_per90'] = players_epl['Gls'] / players_epl['Min'] * 90

In [75]:
players_epl[players_epl['Min'] >= 450][['Player','Squad','Min','Gls','Gls_per90','Ast','Ast_per90']].sort_values('Gls_per90', ascending=False).head(10)

,Player,Squad,Min,Gls,Gls_per90,Ast,Ast_per90
1104,Erling Haaland,Manchester City,2953,27,0.822892,8,0.243820
2016,William Osula,Newcastle United,819,7,0.769231,0,0.000000
179,Taiwo Awoniyi,Nottingham Forest,494,4,0.728745,1,0.182186
1283,Eli Junior Kroupi,Bournemouth,1672,13,0.699761,0,0.000000
2580,Igor Thiago,Brentford,3282,22,0.603291,1,0.027422
2418,Benjamin Šeško,Manchester United,1643,11,0.602556,1,0.054778
1103,Viktor Gyökeres,Arsenal,2224,14,0.566547,1,0.040468
892,Zian Flemming,Burnley,1768,11,0.559955,0,0.000000
807,Hugo Ekitike,Liverpool,1803,11,0.549085,4,0.199667
1609,Donyell Malen,Aston Villa,656,4,0.548780,1,0.137195

In [76]:
[c for c in players_epl.columns if 'per90' in c]

['Ast_per90', 'Sh_per90', 'Gls_per90']

In [77]:
standings = team_matches.groupby('team').agg(
    MP=('points','count'),
    W=('result', lambda x: (x=='W').sum()),
    D=('result', lambda x: (x=='D').sum()),
    L=('result', lambda x: (x=='L').sum()),
    GF=('goals_for','sum'),
    GA=('goals_against','sum'),
    Pts=('points','sum'),
).reset_index()

standings['GD'] = standings['GF'] - standings['GA']
standings = standings.sort_values(['Pts','GD','GF'], ascending=False).reset_index(drop=True)
standings.insert(0, 'Rank', standings.index + 1)
standings

    Rank                     team  MP   W   D   L  GF  GA  Pts  GD
0      1                  Arsenal  38  26   7   5  71  27   85  44
1      2          Manchester City  38  23   9   6  77  35   78  42
2      3        Manchester United  38  20  11   7  69  50   71  19
3      4              Aston Villa  38  19   8  11  56  49   65   7
4      5                Liverpool  38  17   9  12  63  53   60  10
5      6              Bournemouth  38  13  18   7  58  54   57   4
6      7               Sunderland  38  14  12  12  42  48   54  -6
7      8                 Brighton  38  14  11  13  52  46   53   6
8      9                Brentford  38  14  11  13  55  52   53   3
9     10                  Chelsea  38  14  10  14  58  52   52   6
10    11                   Fulham  38  15   7  16  47  51   52  -4
11    12         Newcastle United  38  14   7  17  53  55   49  -2
12    13                  Everton  38  13  10  15  47  50   49  -3
13    14                    Leeds  38  11  14  13  49  56   47  -7
14    15           Crystal Palace  38  11  12  15  41  51   45 -10
15    16        Nottingham Forest  38  11  11  16  48  51   44  -3
16    17                Tottenham  38  10  11  17  48  57   41  -9
17    18                 West Ham  38  10   9  19  46  65   39 -19
18    19                  Burnley  38   4  10  24  38  75   22 -37
19    20  Wolverhampton Wanderers  38   3  11  24  27  68   20 -41

In [78]:
players_epl.to_csv('players_clean.csv', index=False)
team_matches.to_csv('team_matches_clean.csv', index=False)
standings.to_csv('standings.csv', index=False)

In [79]:
players = pd.read_csv('players_clean.csv')
players = players.rename(columns={
    'Player': 'player_name', 'Squad': 'team_name', 'Pos': 'position',
    'Nation': 'nation', 'Age': 'age', 'MP': 'matches_played',
    'Min': 'minutes', 'Gls': 'goals', 'Ast': 'assists',
    'G+A': 'goal_contributions', 'Sh': 'shots', 'SoT': 'shots_on_target',
    'CrdY': 'yellow_cards', 'CrdR': 'red_cards',
    'TklW': 'tackles_won', 'Int': 'interceptions', 'Fls': 'fouls'
})
players.to_csv('players_clean_v2.csv', index=False)

In [80]:
from google.colab import files
files.download('players_clean.csv')
files.download('team_matches_clean.csv')
files.download('standings.csv')